apiVersion: skaffold/v1beta7
kind: Config

profiles:
  - name: testk8s

    build:
      artifacts:
      - image: openapiv2-example
        context: ./
      tagPolicy:
        sha256: {}

    deploy:
      kubectl:
        manifests:
          - ./k8s/deployment.yaml
        flags:
          global: ['--namespace=skaffolddebug']

  - name: publish

    build:
      artifacts:
      - image: openapiv2-example
        context: ./
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.SEMVER}}"
      local: {}
  
  - name: cloudbuild

    build:
      googleCloudBuild: {}